apiVersion: v2
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 3
  minReadySeconds: 10
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      MaxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
        version: 1.0
    spec:
      containers:
      - name: hello-pos
        image: neggs/helloworld:latest
        ports: 
        - containerPort: 8080
